#!/usr/bin/env python3

# Convert json log entries typically output by DI CMS containers to line-style logs
# more readable by humains.
#
# Reads on stdin, output on stdout.
# Input lines that are not json are copied on output without parsing.
#
# Sample:
# `kubectl logs ads-ads-rest-api-fbb5c8688-8ngw6  -f | jsonlogs2lines`

import json
import sys
import os
import re
import string

# For debug of this script, print the input json before the processed output
DUMP_JSON = os.environ.get('DUMP_JSON')


def get_timestamp(e):
    try:
        return e['@timestamp']
    except KeyError:
        try:
            return e['ibm_datetime']
        except:
            return e['eventTime']

def find(path, json):
    # recursive search if the log is structured
    try:
        key = path[:path.index(".")]
        val = json[key]
        if isinstance(val, dict):
            return find(path[path.index(".") + 1:], val)
        else:
            return val
    except ValueError:
        return json.get(path, "")
    except KeyError:
        try:
            return json.get(path, "")
        except KeyError:
            return "-"


def decode_raw_lines(lines):
    msg = bytearray()
    for l in lines:
        l = l.strip()
        l = l[6:54].strip()
        codes_str = re.split(" +", l)
        # print(codes_str)
        for i in codes_str:
            c = int(i, 16)
            if chr(c) in string.printable:
                msg.append(c)
            else:
                msg.append(ord('?'))

    return msg.decode('ascii', 'ignore')


def liberty_access_logs(j):
    path = j.get('ibm_uriPath', '')
    if (not path.endswith('alive') and not path.endswith('ready')) or ('-p' in sys.argv or '-probes' in sys.argv):
        print(
            f"{get_timestamp(j)} {j.get('ibm_uriPath', '')} {j.get('ibm_userAgent', '')} {j.get('ibm_elapsedTime', '')}  {j.get('ibm_responseCode', '')} {j.get('correlationId', '')}")


def ecs_access_logs(j):
    path = find('url.path', j)
    if (not path.endswith('alive') and not path.endswith('ready') and not path == '/metrics') or ( '-p' in sys.argv or '-probes' in sys.argv):
        print(
            f"{get_timestamp(j)} {find('http.request.method', j)} {find('url.path', j)} {find('agent.type', j)} {find('event.duration', j)} {find('http.response.status_code', j)} {j.get('correlation-id', '')}")


def liberty_log(j):
    query_string = j.get('ibm_queryString', '')
    if query_string:
        query_string = '?' + query_string
    print(
        f"{get_timestamp(j)} {find('hostname', j)} {j.get('type', '')} [{j.get('logger_name', '')}] {j.get('ibm_uriPath', '')}{query_string} {j.get('ibm_responseCode', '')} {j.get('ibm_elapsedTime', '')} - {j.get('correlation-id', '')} - {j.get('level', '')}: {j.get('message', '<no msg>')}")
    print_stack(j)
    

def default_log(j):
    query_string = find('url.query', j)
    if query_string:
        query_string = '?' + query_string
    print(
        f"{get_timestamp(j)} {find('log.type', j)} [{find('logger.name', j)}] {find('url.path', j)}{query_string}  - {j.get('correlation-id', '')} - {find('log.level', j)}: {j.get('message', '<no msg>')}")
    print_stack(j)


def print_stack(j):
    stack_trace = j.get('stack_trace')
    if not print_stack_lines(stack_trace):
        stack_trace = j.get('error.stack_trace')
        if not print_stack_lines(stack_trace):
            try: 
                stack_trace = j['error']['stack_trace']
                print_stack_lines(stack_trace)
            except:
                pass
        

def print_stack_lines(stack_trace):
    if stack_trace:
        for l in stack_trace.split('\n'):
            print("   ", l)
        return True
    return False

rawlines = None

for l in sys.stdin:
    try:
        j = json.loads(l[:-1])
        if DUMP_JSON:
            print(l)
        # accesslog
        logType = j.get('log.type', '')
        if logType == 'accesslog' or logType == 'liberty_accesslog':
            ecs_access_logs(j)
        else:
            default_log(j)
    except json.decoder.JSONDecodeError:
        l = l[:-1]
        if rawlines is not None:
            if l == ")":
                print(decode_raw_lines(rawlines))
                print(l)
                rawlines = None
            else:  # FIXME check this is a raw data line
                rawlines.append(l)
        elif "Plaintext before ENCRYPTION (" in l or "Plaintext after DECRYPTION (" in l:
            rawlines = []
            print(l)
        else:
            print("LINE:", l[:-1])
