apiVersion: ads.ibm.com/v1
kind: AutomationDecisionService
metadata:
  name: ads
  namespace: ads
spec:
  license:
    accept: true
  version: "25.0.0"

  zen:
    block_storage_classname: managed-csi

  decision_designer:
    enabled: true
    database:
      embedded: true

  decision_runtime:
    enabled: true
    database:
      embedded: true
